### ISSUE TITLE
very slow scrolling speed with VirtualizedWrapPanel

### ISSUE THREAD

**Issue by julesx** [digimezzo/WPFControls#13]
I believe the scroll speed should be adjusted based on the child height setting.

currently, it scrolls a tiny amount when it should be scrolling around the height of one child item.

**Comment by julesx** [comment]
this virtualized wrap panel is already amazing, if this could be improved it would be fantastic

**Comment by digimezzo** [comment]
This should be easy to do. I'll have a look at it this weekend.

**Comment by digimezzo** [comment]
I fixed this in 24fad3974fa88b1488172d1436338810af01a47a BY default the VirtualizedWrapPanel scrolls by child height, unless you explicitly specify a ScrollOffset in the WrapPanel, then it will scroll by the specified offset in pixels.
